rpc:
  enable: false
  bind: 127.0.0.1:8080
debug: false
interval: 20
out_put_path: ./
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
live_rooms:
# qulity默认为1
# B站1代表原画PRO(HEVC)优先, 其他为原画(AVC)
# 原画PRO会保存为.ts文件, 原画为.flv
# HEVC相比AVC体积更小, 减少35%体积, 画质相当, 但是B站转码有时候会崩
- url: https://live.bilibili.com/22603245
  is_listening: true
  quality: 1 
- url: https://live.bilibili.com/21452505
  is_listening: true
  quality: 2
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
timeout_in_us: 60000000
